### ISSUE TITLE
Change the site's title

### ISSUE THREAD

**Issue by akshgpt7** [MLH-Fellowship/prep-project-23.APR.PREP.1#27]
The title on the tab currently shows "React App". Can we change that to a more relevant name?
<img width="237" alt="image" src="https://user-images.githubusercontent.com/20405311/232863274-0632c407-b9fb-48a6-934f-ca21da0d9415.png">

**Comment by apala7778** [comment]
I would like to work on this. can you assign me?

**Comment by k-deepak04** [comment]
i would like to work on it i will create a pr shortly. :)

**Comment by k-deepak04** [comment]
@akshgpt7 check #30 .

**Comment by ttn-ttn** [comment]
@k-deepak04 I don't see how "MLH Prep" is a relevant name for a weather app.

**Comment by k-deepak04** [comment]
@ttn-ttn Give me a valid name I'll put it there

**Comment by ttn-ttn** [comment]
@k-deepak04 when we decide on the name, we can put it there ourselves. It's a one-line change.

This is a project by and for the participants on MLH Prep Program. If you have a substantial contribution to make, open a PR and it may be accepted (I'm not sure about the policy on that). However, please refrain from trivial contributions, as those don't help us and only create noise.

Also, please don't open issues unless there is something objectively wrong with the webapp. The design has already been decided and it's being worked on. Opening issues to propose changes to it only creates noise, again.

**Comment by k-deepak04** [comment]
@ttn-ttn Got that.
