### ISSUE TITLE
Fix UI for homepage to match figma design

### ISSUE THREAD

**Issue by ThGreatExplorer** [MLH-Fellowship/prep-project-23.APR.PREP.1#44]
Figma design: [UI](https://www.figma.com/file/PfBFdcZuRr1koHxuHY7hLJ/Trip-planner?node-id=0-1)

Homepage only!

![image](https://user-images.githubusercontent.com/73237120/233451180-c6dfa869-4375-4cab-97af-2eac5ef3298f.png)

**Comment by kristinlam** [comment]
@ThGreatExplorer I can work on this!
