### ISSUE TITLE
Improve mobile usability

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-project-23.APR.PREP.1#7]
The card that displays the weather information isn't responsive. It's far too narrow on mobile, and too wide on desktop. Can you look into making it be an appropriate size on all screen sizes.

**Comment by Ankur6702** [comment]
Hey @akshgpt7 , can you assign this issue to me?

**Comment by archikirar30** [comment]
Hey @akshgpt7 , I also want to work on it, can you assign it to me too?
